# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '20 9 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message:  "This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in next 30 days."
        stale-pr-message: "This PR is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in next 30 days."
        close-issue-message: 'This issue was closed because it has been stalled with no activity.'
        close-pr-message: 'This PR was closed because it has been stalled with no activity.'
        stale-issue-label: 'Stale - Do Not Merge'
        stale-pr-label: 'Stale - Do Not Merge'
        days-before-stale: 30
        days-before-close: 60
        exempt-issue-labels: "help wanted,question,in progress,do not merge, good first issue"
        exempt-pr-labels: "help wanted,question,in progress,do not merge, good first issue"
